[package]
build  ="build.rs"
edition="2021"
name   ="lm"
version="0.1.0"

[dependencies]
derive_builder="0.20.2"
libc          ="0.2.159"
ndarray       ="0.16.1"
ndarray-linalg="0.16.0"
openblas-src  ="0.10.9"
thiserror     ="1.0.64"

[build-dependencies]
cc="1.0"
